# 老子天下第一萌著
import time
import random
print("老子天下第一萌著")
print("欢迎使用未来科技")
time.sleep(1)
print("我是超级计算器")
time.sleep(1)
print("请输入数字选择计算方式")
time.sleep(1)
time.sleep(1)
w=1
while w==1:
 print("1.加法")
 print("2.减法")
 print("3.乘法")
 print("4.除法")
 print("5.汉字十进制编码查询")
 print("6.十进制转换为字符")
 print("7.求二元一次方程实数根")
 print("8.解二元一次方程组")
 print("请直接输入序号")
 a=float(input())
 if a==1:
        print("请输入第一个数")
        b = float(input())
        print("请输入第二个数")
        c = float(input())
        d = float(b+c)
        print("答案是")
        print(d)
        time.sleep(2)
        print("请选择下一步操作")
        print("1.继续计算")
        print("2退出")
        w=int(input())
 elif a==2:
        print("请输入第一个数")
        b = float(input())
        print("请输入第二个数")
        c = float(input())
        d = float(b - c)
        print("答案是")
        print(d)
        time.sleep(2)
        print("请选择下一步操作")
        print("1.继续计算")
        print("2退出")
        w = int(input())
 elif a==3:
        print("请输入第一个数")
        b = float(input())
        print("请输入第二个数")
        c = float(input())
        d = float(b * c)
        print("答案是")
        print(d)
        time.sleep(2)
        print("请选择下一步操作")
        print("1.继续计算")
        print("2退出")
        w = int(input())
 elif a==4:
        print("请输入第一个数")
        b = float(input())
        print("请输入第二个数")
        c = float(input())
        d = float(b / c)
        print("答案是")
        print(d)
        time.sleep(2)
        print("请选择下一步操作")
        print("1.继续计算")
        print("2退出")
        w = int(input())
 elif   a==5:
        print("请输入需要查询的字符")
        e = str(input())
        print(ord(e))
        time.sleep(2)
        print("请选择下一步操作")
        print("1.继续计算")
        print("2退出")
        w = int(input())
 elif   a==6:
        print("请输入十进制编码")
        f = int(input())
        print(chr(f))
        time.sleep(2)
        print("请选择下一步操作")
        print("1.继续计算")
        print("2退出")
        w = int(input())
 elif   a==7:
        print("请输入a")
        a = float(input())
        print("请输入b")
        b = float(input())
        print("请输入c")
        c = float(input())
        delta = b*b-4*a*c
        if delta < 0:
               print("没有实数根")
               time.sleep(2)
               print("请选择下一步操作")
               print("1.继续计算")
               print("2退出")
               w = int(input())

        elif delta == 0:
               print("有一个实数根")
               x = (-b) / 2 * a
               print(x)
               time.sleep(2)
               print("请选择下一步操作")
               print("1.继续计算")
               print("2退出")
               w = int(input())
        else :
               print("有两个实数根")
               x1 = (-b+delta**0.5)/(2*a)
               x2 = (-b-delta**0.5)/(2*a)
               print(x1)
               print(x2)
               time.sleep(2)
               print("请选择下一步操作")
               print("1.继续计算")
               print("2退出")
               w = int(input())
 elif   a==8:
        print("根据表达式，正确输入a、b、c、d、m、n")
        print("ax+by=m")
        print("cx+dy=n")
        time.sleep(1)
        print("请依次输入a、b、c、d、m、n，并且注意符号")
        print("请输入a")
        a = float(input())
        print("请输入b")
        b = float(input())
        print("请输入c")
        c = float(input())
        print("请输入d")
        d = float(input())
        print("请输入m")
        m = float(input())
        print("请输入n")
        n = float(input())
        x = (m*d-b*n)/(a*d-b*c)
        y = (m*c-a*n)/(b*c-a*d)
        print("x=")
        print(x)
        print("y=")
        print(y)
        time.sleep(2)
        print("请选择下一步操作")
        print("1.继续计算")
        print("2退出")
        w = int(input())
 else     :
        print("请输入正确的序号")
        print("请选择下一步操作")
        time.sleep(2)
        w = 1;

